#ifndef _GV_LIB_CONF_H_
#define _GV_LIB_CONF_H_


#define GV_LIB_USE_LOGGER

#define GV_LIB_USE_SSD1306 1

#define GV_LIB_USE_ROTARY_ENCODER

#define GV_LIB_USE_LED_PWM

#define GV_LIB_USE_WAV_READER_SPI

#define GV_LIB_USE_THREAD_HANDLER

#define GV_LIB_USE_PWM_OUTPUT_AUDIO

#ifdef GV_LIB_USE_PWM_OUTPUT_AUDIO

#define GV_LIB_USE_8BIT_PWM 1

#define GV_LIB_USE_16BIT_PWM 0

#define GV_LIB_USE_PWM_AUDIO_LOGGER 1

#endif // GV_LIB_USE_PWM_OUTPUT_AUDIO

#define GV_LIB_USE_LFSR 1

#endif // _GV_LIB_CONF_H_