function(check_macro_defined macro_name result_var)
    file(READ ${GV_LIB_CONF_FILE} gv_lib_conf_content)
    string(FIND "${gv_lib_conf_content}" "#define ${macro_name}" macro_pos)
    if (NOT macro_pos EQUAL -1)
        set(${result_var} TRUE PARENT_SCOPE)
    else()
        set(${result_var} FALSE PARENT_SCOPE)
    endif()
endfunction()


function(check_macro_defined_global macro_name result_var)
    file(READ ${GV_LIB_CONF_FILE} gv_lib_conf_content)
    string(FIND "${gv_lib_conf_content}" "#define ${macro_name}" macro_pos)
    if (NOT macro_pos EQUAL -1)
        set(${result_var} TRUE CACHE INTERNAL "Global variable set by check_macro_defined_global")
    else()
        set(${result_var} FALSE CACHE INTERNAL "Global variable set by check_macro_defined_global")
    endif()
endfunction()